import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Next Blog App",
	description: "Generated by create next app",
};

export default function BlogLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header className="bg-blue-500 text-4xl py-5 text-center" >
					Header
				</header>
				{children}
				<footer className="bg-gray-500 text-4xl py-5 text-center fixed bottom-0 w-full" >
					Footer
				</footer>
			</body>
		</html>
	);
}
